In [1]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt

# Nominal-->OneHotEncoding

In [2]:
df=pd.read_csv('titanic.csv',usecols=['Fare','Age','Sex','Survived'])

In [3]:
df.head()

Survived     Sex   Age     Fare
0         0    male  34.5   7.8292
1         1  female  47.0   7.0000
2         0    male  62.0   9.6875
3         0    male  27.0   8.6625
4         1  female  22.0  12.2875

In [4]:
df['Sex'].unique()

array(['male', 'female'], dtype=object)

In [5]:
a = pd.get_dummies(df['Sex'],drop_first=True)

In [6]:
a

male
0       1
1       0
2       1
3       1
4       0
..    ...
413     1
414     0
415     1
416     1
417     1

[418 rows x 1 columns]

In [7]:
a.head()

male
0     1
1     0
2     1
3     1
4     0

In [8]:
df = pd.concat([df,a],axis=1)

In [9]:
df.head()

Survived     Sex   Age     Fare  male
0         0    male  34.5   7.8292     1
1         1  female  47.0   7.0000     0
2         0    male  62.0   9.6875     1
3         0    male  27.0   8.6625     1
4         1  female  22.0  12.2875     0

## Using With Sklearn

In [10]:
from sklearn.preprocessing import OneHotEncoder

In [11]:
df=pd.read_csv('titanic.csv',usecols=['Fare','Age','Sex','Survived'])

In [12]:
reg = OneHotEncoder(categories = 'auto', drop='first',sparse=False,handle_unknown='error')

In [13]:
reg.fit(df['Sex'].values.reshape(-1,1))

OneHotEncoder(drop='first', sparse=False)

In [14]:
a = reg.transform(df['Sex'].values.reshape(-1,1))

In [15]:
a

array([[1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],

In [16]:
c = pd.DataFrame(a)

In [17]:
c.columns = reg.get_feature_names()

In [18]:
c

x0_male
0        1.0
1        0.0
2        1.0
3        1.0
4        0.0
..       ...
413      1.0
414      0.0
415      1.0
416      1.0
417      1.0

[418 rows x 1 columns]

In [19]:
df.head()

Survived     Sex   Age     Fare
0         0    male  34.5   7.8292
1         1  female  47.0   7.0000
2         0    male  62.0   9.6875
3         0    male  27.0   8.6625
4         1  female  22.0  12.2875

## Using with Feature Engine

In [20]:
from feature_engine.encoding import OneHotEncoder

In [21]:
df=pd.read_csv('titanic.csv',usecols=['Fare','Age','Sex','Survived'])

In [22]:
reg = OneHotEncoder(drop_last = True , variables=())

In [23]:
reg.fit(df)

OneHotEncoder(drop_last=True, variables=())

In [24]:
reg.transform(df)

Survived   Age      Fare  Sex_male
0           0  34.5    7.8292         1
1           1  47.0    7.0000         0
2           0  62.0    9.6875         1
3           0  27.0    8.6625         1
4           1  22.0   12.2875         0
..        ...   ...       ...       ...
413         0   NaN    8.0500         1
414         1  39.0  108.9000         0
415         0  38.5    7.2500         1
416         0   NaN    8.0500         1
417         0   NaN   22.3583         1

[418 rows x 4 columns]

# Odinal Encoding

In [25]:
df=pd.read_csv('customer.csv')

In [26]:
df.head()

age  gender   review education purchased
0   30  Female  Average    School        No
1   68  Female     Poor        UG        No
2   70  Female     Good        PG        No
3   72  Female     Good        PG        No
4   16  Female  Average        UG        No

In [27]:
from sklearn.preprocessing import OrdinalEncoder

In [28]:
reg = OrdinalEncoder()

In [29]:
reg.fit(df['review'].values.reshape(-1,1))

OrdinalEncoder()

In [30]:
a=reg.transform(df['review'].values.reshape(-1,1))

In [31]:
a

array([[0.],
       [2.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [1.],
       [1.],
       [2.],
       [0.],
       [2.],
       [2.],
       [2.],
       [2.],
       [1.],
       [2.],
       [0.],
       [0.],
       [2.],
       [1.],
       [0.],
       [1.],
       [2.],
       [2.],
       [2.],
       [0.],
       [0.],
       [2.],
       [0.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [1.],
       [2.],
       [1.],
       [1.],
       [1.],
       [2.],
       [0.],
       [2.],
       [2.],
       [1.],
       [1.],
       [1.]])

In [32]:
c = pd.DataFrame(a,columns = ['Review coverted'])

In [33]:
df=pd.concat([df,c],axis=1)

In [34]:
df.head()

age  gender   review education purchased  Review coverted
0   30  Female  Average    School        No              0.0
1   68  Female     Poor        UG        No              2.0
2   70  Female     Good        PG        No              1.0
3   72  Female     Good        PG        No              1.0
4   16  Female  Average        UG        No              0.0

In [35]:
df['review'].unique()

array(['Average', 'Poor', 'Good'], dtype=object)

In [36]:
df['Review coverted'].unique()

array([0., 2., 1.])

# Lable Encoding

In [37]:
import warnings
warnings.filterwarnings('ignore')

In [38]:
df = pd.read_csv('customer.csv')

In [39]:
df.head()

age  gender   review education purchased
0   30  Female  Average    School        No
1   68  Female     Poor        UG        No
2   70  Female     Good        PG        No
3   72  Female     Good        PG        No
4   16  Female  Average        UG        No

In [40]:
df['purchased'].unique()

array(['No', 'Yes'], dtype=object)

In [41]:
from sklearn.preprocessing import LabelEncoder

In [42]:
reg = LabelEncoder()

In [43]:
reg.fit(df['purchased'].values.reshape(-1,1))

LabelEncoder()

In [44]:
a = reg.transform(df['purchased'].values.reshape(-1,1))

In [45]:
a

array([0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 1, 1, 0])

In [46]:
df['purchased'][:10]

0     No
1     No
2     No
3     No
4     No
5    Yes
6     No
7    Yes
8     No
9    Yes
Name: purchased, dtype: object

In [47]:
f = pd.DataFrame(a,columns=['target'])

In [48]:
df = pd.concat([df,f],axis=1)

In [49]:
df.head()

age  gender   review education purchased  target
0   30  Female  Average    School        No       0
1   68  Female     Poor        UG        No       0
2   70  Female     Good        PG        No       0
3   72  Female     Good        PG        No       0
4   16  Female  Average        UG        No       0

# Count or Frequency Encoding 

In [50]:
df = pd.read_csv('house_price.csv',usecols=['Neighborhood','Exterior1st'])

In [51]:
df.head()

Neighborhood Exterior1st
0      CollgCr     VinylSd
1      Veenker     MetalSd
2      CollgCr     VinylSd
3      Crawfor     Wd Sdng
4      NoRidge     VinylSd

In [52]:
df['Neighborhood'].value_counts()

NAmes      225
CollgCr    150
OldTown    113
Edwards    100
Somerst     86
Gilbert     79
NridgHt     77
Sawyer      74
NWAmes      73
SawyerW     59
BrkSide     58
Crawfor     51
Mitchel     49
NoRidge     41
Timber      38
IDOTRR      37
ClearCr     28
SWISU       25
StoneBr     25
MeadowV     17
Blmngtn     17
BrDale      16
Veenker     11
NPkVill      9
Blueste      2
Name: Neighborhood, dtype: int64

In [53]:
len(df['Neighborhood'].value_counts())

25

In [54]:
for i in df.columns:
    print(f'Number of Unique Values in {i} = ',len(df[i].unique()))

Number of Unique Values in Neighborhood =  25
Number of Unique Values in Exterior1st =  15


In [55]:
value = df['Neighborhood'].value_counts().to_dict()

In [56]:
value

{'NAmes': 225,
 'CollgCr': 150,
 'OldTown': 113,
 'Edwards': 100,
 'Somerst': 86,
 'Gilbert': 79,
 'NridgHt': 77,
 'Sawyer': 74,
 'NWAmes': 73,
 'SawyerW': 59,
 'BrkSide': 58,
 'Crawfor': 51,
 'Mitchel': 49,
 'NoRidge': 41,
 'Timber': 38,
 'IDOTRR': 37,
 'ClearCr': 28,
 'SWISU': 25,
 'StoneBr': 25,
 'MeadowV': 17,
 'Blmngtn': 17,
 'BrDale': 16,
 'Veenker': 11,
 'NPkVill': 9,
 'Blueste': 2}

In [57]:
df['Neighborhood'] = df['Neighborhood'].map(value)

In [58]:
df.head()

Neighborhood Exterior1st
0           150     VinylSd
1            11     MetalSd
2           150     VinylSd
3            51     Wd Sdng
4            41     VinylSd

# Frequency = Totalnique/ len(df)

In [59]:
fre = (df['Exterior1st'].value_counts()/len(df)).to_dict()

In [60]:
fre

{'VinylSd': 0.3527397260273973,
 'HdBoard': 0.15205479452054796,
 'MetalSd': 0.1506849315068493,
 'Wd Sdng': 0.1410958904109589,
 'Plywood': 0.07397260273972603,
 'CemntBd': 0.04178082191780822,
 'BrkFace': 0.03424657534246575,
 'WdShing': 0.01780821917808219,
 'Stucco': 0.017123287671232876,
 'AsbShng': 0.0136986301369863,
 'BrkComm': 0.0013698630136986301,
 'Stone': 0.0013698630136986301,
 'CBlock': 0.0006849315068493151,
 'ImStucc': 0.0006849315068493151,
 'AsphShn': 0.0006849315068493151}

In [61]:
df['Exterior1st'] = df ['Exterior1st'].map(fre)

In [62]:
df.head()

Neighborhood  Exterior1st
0           150     0.352740
1            11     0.150685
2           150     0.352740
3            51     0.141096
4            41     0.352740

## Using Feature Engine

In [63]:
from feature_engine.encoding import CountFrequencyEncoder

In [64]:
df = pd.read_csv('house_price.csv',usecols=['Neighborhood','Exterior1st'])

In [65]:
reg = CountFrequencyEncoder(encoding_method = 'count',variables=['Neighborhood','Exterior1st'])

In [66]:
reg.fit(df)

CountFrequencyEncoder(variables=['Neighborhood', 'Exterior1st'])

In [67]:
reg.encoder_dict_

{'Neighborhood': {'NAmes': 225,
  'CollgCr': 150,
  'OldTown': 113,
  'Edwards': 100,
  'Somerst': 86,
  'Gilbert': 79,
  'NridgHt': 77,
  'Sawyer': 74,
  'NWAmes': 73,
  'SawyerW': 59,
  'BrkSide': 58,
  'Crawfor': 51,
  'Mitchel': 49,
  'NoRidge': 41,
  'Timber': 38,
  'IDOTRR': 37,
  'ClearCr': 28,
  'SWISU': 25,
  'StoneBr': 25,
  'MeadowV': 17,
  'Blmngtn': 17,
  'BrDale': 16,
  'Veenker': 11,
  'NPkVill': 9,
  'Blueste': 2},
 'Exterior1st': {'VinylSd': 515,
  'HdBoard': 222,
  'MetalSd': 220,
  'Wd Sdng': 206,
  'Plywood': 108,
  'CemntBd': 61,
  'BrkFace': 50,
  'WdShing': 26,
  'Stucco': 25,
  'AsbShng': 20,
  'BrkComm': 2,
  'Stone': 2,
  'CBlock': 1,
  'ImStucc': 1,
  'AsphShn': 1}}

In [68]:
reg.transform(df)

Neighborhood  Exterior1st
0              150          515
1               11          220
2              150          515
3               51          206
4               41          515
...            ...          ...
1455            79          515
1456            73          108
1457            51           61
1458           225          220
1459           100          222

[1460 rows x 2 columns]