In [2]:
import numpy as np
import matplotlib.pyplot as plt

In [3]:
df=pd.read_csv('titanic.csv')

In [4]:
df.head()

PassengerId  Survived  Pclass  \
0          892         0       3   
1          893         1       3   
2          894         0       2   
3          895         0       3   
4          896         1       3   

                                           Name     Sex   Age  SibSp  Parch  \
0                              Kelly, Mr. James    male  34.5      0      0   
1              Wilkes, Mrs. James (Ellen Needs)  female  47.0      1      0   
2                     Myles, Mr. Thomas Francis    male  62.0      0      0   
3                              Wirz, Mr. Albert    male  27.0      0      0   
4  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female  22.0      1      1   

    Ticket     Fare Cabin Embarked  
0   330911   7.8292   NaN        Q  
1   363272   7.0000   NaN        S  
2   240276   9.6875   NaN        Q  
3   315154   8.6625   NaN        S  
4  3101298  12.2875   NaN        S

In [5]:
df=df[['Cabin','Sex','Embarked','Survived']]

In [6]:
df.head()

Cabin     Sex Embarked  Survived
0   NaN    male        Q         0
1   NaN  female        S         1
2   NaN    male        Q         0
3   NaN    male        S         0
4   NaN  female        S         1

In [7]:
df.isnull().sum()

Cabin       327
Sex           0
Embarked      0
Survived      0
dtype: int64

In [8]:
df['Sex'].unique()

array(['male', 'female'], dtype=object)

In [9]:
df['Sex'].value_counts()

male      266
female    152
Name: Sex, dtype: int64

In [15]:
for i in df.columns:
    print(i , ':', len(df[i].unique()), 'labels')

Cabin : 77 labels
Sex : 2 labels
Embarked : 3 labels
Survived : 2 labels


In [16]:
df['Embarked'].unique()

array(['Q', 'S', 'C'], dtype=object)

In [17]:
df['Cabin'].unique()

array([nan, 'B45', 'E31', 'B57 B59 B63 B66', 'B36', 'A21', 'C78', 'D34',
       'D19', 'A9', 'D15', 'C31', 'C23 C25 C27', 'F G63', 'B61', 'C53',
       'D43', 'C130', 'C132', 'C101', 'C55 C57', 'B71', 'C46', 'C116',
       'F', 'A29', 'G6', 'C6', 'C28', 'C51', 'E46', 'C54', 'C97', 'D22',
       'B10', 'F4', 'E45', 'E52', 'D30', 'B58 B60', 'E34', 'C62 C64',
       'A11', 'B11', 'C80', 'F33', 'C85', 'D37', 'C86', 'D21', 'C89',
       'F E46', 'A34', 'D', 'B26', 'C22 C26', 'B69', 'C32', 'B78',
       'F E57', 'F2', 'A18', 'C106', 'B51 B53 B55', 'D10 D12', 'E60',
       'E50', 'E39 E41', 'B52 B54 B56', 'C39', 'B24', 'D28', 'B41', 'C7',
       'D40', 'D38', 'C105'], dtype=object)

In [18]:
#### This Type of Varibles definitely goin to Harm our model

In [23]:
from sklearn.model_selection import train_test_split

In [25]:
x=df.drop(['Survived'],axis=1)
y=df['Survived']

In [26]:
x_train,x_test,y_train,y_test=train_test_split(x,y, test_size=0.33,random_state=42)

In [27]:
x_train.shape , x_test.shape

((280, 3), (138, 3))

In [29]:
sex_train_value = [i for i in x_train['Sex'].unique() if i not in x_test['Sex'].unique()]
sex_train_value

[]

In [30]:
embarked_train_value = [j for j in x_train['Embarked'].unique() if j not in x_test['Embarked'].unique()]
embarked_train_value

[]

In [33]:
cabin_train_value = [k for k in x_train['Cabin'].unique() if k not in x_test['Cabin'].unique()]
len(cabin_train_value)

49

In [37]:
# 49 lables present in trainning data and not there in test data

In [38]:
cabin_test_value = [k1 for k1 in x_test['Cabin'].unique()  if k1 not in x_train['Cabin'].unique()]

In [39]:
len(cabin_test_value)

22

In [40]:
# 22 lables present in test data and there in trainning data

In [41]:
# Solving This Kind of Techiniques

In [42]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [43]:
df=pd.read_csv('titanic.csv')

In [44]:
df.head()

PassengerId  Survived  Pclass  \
0          892         0       3   
1          893         1       3   
2          894         0       2   
3          895         0       3   
4          896         1       3   

                                           Name     Sex   Age  SibSp  Parch  \
0                              Kelly, Mr. James    male  34.5      0      0   
1              Wilkes, Mrs. James (Ellen Needs)  female  47.0      1      0   
2                     Myles, Mr. Thomas Francis    male  62.0      0      0   
3                              Wirz, Mr. Albert    male  27.0      0      0   
4  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female  22.0      1      1   

    Ticket     Fare Cabin Embarked  
0   330911   7.8292   NaN        Q  
1   363272   7.0000   NaN        S  
2   240276   9.6875   NaN        Q  
3   315154   8.6625   NaN        S  
4  3101298  12.2875   NaN        S

In [45]:
df['Cabin'].unique()

array([nan, 'B45', 'E31', 'B57 B59 B63 B66', 'B36', 'A21', 'C78', 'D34',
       'D19', 'A9', 'D15', 'C31', 'C23 C25 C27', 'F G63', 'B61', 'C53',
       'D43', 'C130', 'C132', 'C101', 'C55 C57', 'B71', 'C46', 'C116',
       'F', 'A29', 'G6', 'C6', 'C28', 'C51', 'E46', 'C54', 'C97', 'D22',
       'B10', 'F4', 'E45', 'E52', 'D30', 'B58 B60', 'E34', 'C62 C64',
       'A11', 'B11', 'C80', 'F33', 'C85', 'D37', 'C86', 'D21', 'C89',
       'F E46', 'A34', 'D', 'B26', 'C22 C26', 'B69', 'C32', 'B78',
       'F E57', 'F2', 'A18', 'C106', 'B51 B53 B55', 'D10 D12', 'E60',
       'E50', 'E39 E41', 'B52 B54 B56', 'C39', 'B24', 'D28', 'B41', 'C7',
       'D40', 'D38', 'C105'], dtype=object)

In [46]:
df['Cabin_replaced'] = df['Cabin'].astype(str).str[0]

In [47]:
df['Cabin_replaced'].unique()

array(['n', 'B', 'E', 'A', 'C', 'D', 'F', 'G'], dtype=object)

In [48]:
df=df[['Cabin' , 'Cabin_replaced' , 'Sex', 'Embarked', 'Survived']]

In [49]:
df.head()

Cabin Cabin_replaced     Sex Embarked  Survived
0   NaN              n    male        Q         0
1   NaN              n  female        S         1
2   NaN              n    male        Q         0
3   NaN              n    male        S         0
4   NaN              n  female        S         1

In [50]:
df.isnull().sum()

Cabin             327
Cabin_replaced      0
Sex                 0
Embarked            0
Survived            0
dtype: int64

In [51]:
df['Sex'].unique()

array(['male', 'female'], dtype=object)

In [52]:
df['Sex'].value_counts()

male      266
female    152
Name: Sex, dtype: int64

In [53]:
for i in df.columns:
    print(i , ':' , (df[i].unique(),'labels'))

Cabin : (array([nan, 'B45', 'E31', 'B57 B59 B63 B66', 'B36', 'A21', 'C78', 'D34',
       'D19', 'A9', 'D15', 'C31', 'C23 C25 C27', 'F G63', 'B61', 'C53',
       'D43', 'C130', 'C132', 'C101', 'C55 C57', 'B71', 'C46', 'C116',
       'F', 'A29', 'G6', 'C6', 'C28', 'C51', 'E46', 'C54', 'C97', 'D22',
       'B10', 'F4', 'E45', 'E52', 'D30', 'B58 B60', 'E34', 'C62 C64',
       'A11', 'B11', 'C80', 'F33', 'C85', 'D37', 'C86', 'D21', 'C89',
       'F E46', 'A34', 'D', 'B26', 'C22 C26', 'B69', 'C32', 'B78',
       'F E57', 'F2', 'A18', 'C106', 'B51 B53 B55', 'D10 D12', 'E60',
       'E50', 'E39 E41', 'B52 B54 B56', 'C39', 'B24', 'D28', 'B41', 'C7',
       'D40', 'D38', 'C105'], dtype=object), 'labels')
Cabin_replaced : (array(['n', 'B', 'E', 'A', 'C', 'D', 'F', 'G'], dtype=object), 'labels')
Sex : (array(['male', 'female'], dtype=object), 'labels')
Embarked : (array(['Q', 'S', 'C'], dtype=object), 'labels')
Survived : (array([0, 1], dtype=int64), 'labels')


In [54]:
df['Embarked'].unique()

array(['Q', 'S', 'C'], dtype=object)

In [55]:
df['Cabin'].unique()

array([nan, 'B45', 'E31', 'B57 B59 B63 B66', 'B36', 'A21', 'C78', 'D34',
       'D19', 'A9', 'D15', 'C31', 'C23 C25 C27', 'F G63', 'B61', 'C53',
       'D43', 'C130', 'C132', 'C101', 'C55 C57', 'B71', 'C46', 'C116',
       'F', 'A29', 'G6', 'C6', 'C28', 'C51', 'E46', 'C54', 'C97', 'D22',
       'B10', 'F4', 'E45', 'E52', 'D30', 'B58 B60', 'E34', 'C62 C64',
       'A11', 'B11', 'C80', 'F33', 'C85', 'D37', 'C86', 'D21', 'C89',
       'F E46', 'A34', 'D', 'B26', 'C22 C26', 'B69', 'C32', 'B78',
       'F E57', 'F2', 'A18', 'C106', 'B51 B53 B55', 'D10 D12', 'E60',
       'E50', 'E39 E41', 'B52 B54 B56', 'C39', 'B24', 'D28', 'B41', 'C7',
       'D40', 'D38', 'C105'], dtype=object)

In [56]:
from sklearn.model_selection import train_test_split

In [57]:
x=df.drop(['Survived'],axis=1)
y=df['Survived']

In [59]:
#x=df.iloc[: , :-1]
#y=df.iloc[:,-1]

In [62]:
x_train,x_test,y_train,y_test=train_test_split(x,y, test_size=0.33,random_state=42)

In [63]:
x_train.shape , x_test.shape

((280, 4), (138, 4))

In [66]:
cabin_train_value = [k for k in x_train['Cabin_replaced'].unique() if k not in x_test['Cabin_replaced'].unique()]
len(cabin_train_value)

1

In [67]:
cabin_train_value = [k for k in x_test['Cabin_replaced'].unique() if k not in x_train['Cabin_replaced'].unique()]
len(cabin_train_value)

0